### ISSUE TITLE
Tidal authentication failed

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#31]
Hi !
I can't connect to Tidal anymore, can you help me? thanks

**Comment by tehkillerbee** [comment]
Hey, you will need to send your log files so I can see what is going wrong. Did it stop working recently?

If you run Mopidy as a system service and are using journald, like most modern Linux systems, you can view the Mopidy log by running:

sudo journalctl -u mopidy

To save the output to a file for sharing, run:

sudo journalctl -u mopidy | tee mopidy.log

**Comment by chicco64** [comment]
Hi !
now it works perfectly, many thanks !

**Comment by tehkillerbee** [comment]
Not sure what you did to fix the issue. 

However, I have noticed that sometimes Tidal connection fails due to missing internet connection (eg. when rebooting the PC, raspberry pi etc. ). In those situations, it helps delaying the mopidy startup or restarting the plugin:

sudo service mopidy restart
