### ISSUE TITLE
MQA, HIFI Playback

### ISSUE THREAD

**Issue by bikebandit101** [tehkillerbee/mopidy-tidal#33]
Hey Tehkillerbee,
Looking the the master and dev fork seems like you & your team(?) are working on getting access for MQA track into Mopidy? Is there anything you need to help this endeavor along? I have very limited programming skills, but if there is something you need to help you, please let me know. This feature would be really great. Thank you for maintaining this Git
Kyle

**Comment by tehkillerbee** [comment]
Hey @bikebandit101  Yes, the dev branch contains some experiments that I did while testing pull request #27 on Python 3. This pull request adds support for MQA / master quality playback in addition to other improvements. However, I have not merged it, as it is currently not working correctly with Python 3 and it requires an unsupported fork of the tidalapi with OAuth login support.

To answer your question, I would very much like to add support for MQA, but since it requires a different login method (OAuth), this feature would have to be added to the python-tidal/tidalAPI module first, before MQA support can be added to mopidy-tidal.

I think a lot of inspiration can be taken from #27 and the forks by the PR auther, as theygives an idea of the changes required for both mopidy-tidal (this plugin) and the fork of python-tidal / tidalapi:
https://github.com/quodrum-glas/mopidy-tidal
https://github.com/quodrum-glas/python-tidal

If the above changes can be added to the python-tidal module, maybe the developers of this module will be interested in merging it in, thus adding support for MQA and OAuth.

I do not have a MQA subscription to test with at this point. If you have a subscription, you may be able to help by testing it, when more progress is made. :)

**Comment by bikebandit101** [comment]
Hey @tehkillerbee ,
I cannot do my much programming, but that might be changing due to a job change and having to learn python. But, what I can offer at the moment, is getting you a MQA subscription to help the development process along. I would be more than happy to beta / alpha testing for the release. My overall goal in this is that Mopidy to support Tidal because [I think] Tidal is the best HiFi streaming service. And, I believe that having Mopidy run the server / MPD for control is a better solution than Volumio because with Rasberry OS still running this enables the Pi to perform other functions such as NAS drive for saving your high quality PCM / DSD files over the network, running a CD drive, and display. Exchange Volumio for Mopidy. Attached is my DAC development project. I am designing the power board to run the DAC, FiFo Pi (Ian Canada - [check out his Github](https://github.com/iancanada/DocumentDownload)) , PI, HDDs, and an optical drive. If you're interested in one of these boards; once I have the PCB mades, I can send you a raw board. 
[DAC Technical Specifications.pdf](https://github.com/tehkillerbee/mopidy-tidal/files/6025306/DAC.Technical.Specifications.pdf)

**Comment by tehkillerbee** [comment]
The ability to test with MQA is definitely necessary, for sure. But I think the main issue is still the OAuth login. So that need to be fixed as the first thing.

Your DAC project look very interesting. I would be glad to test a board. Since my main occupation is an EE, I do have the equipment to assemble it. I assume you collaborate with Ian Canada?

**Comment by bikebandit101** [comment]
Sure, I will send you a board and BOM when I get it done. I didnt really collaborate with Ian Canada rather brought his parts. By training I am R&D engineer in Med Device. 
I can reach out to Tidal about API access? Is there any in particular I should ask or is there a better way I can assist. Thanks!

**Comment by tehkillerbee** [comment]
I doubt that reaching out to Tidal would give us any more information. But there are a couple of instructions listed here: https://github.com/tidal-engineering/passport-tidal. There is also a discussion here regarding getting API access https://github.com/MusicPlayerDaemon/MPD/issues/545
Quoting jonaski in the above thread: "I don't think Tidal would approve an open source project where the client id can be seen in the source code. And without the client id no-one can use it."

In any case, the tidalAPI has been reverse engineered by DerNuntius and others (see https://github.com/Fokka-Engineering/TIDAL/wiki for more information). I would probably look at https://github.com/Fokka-Engineering/TIDAL/wiki/auth-token for more information about the auth process and see if a similar approach can be implemented for the python-tidal plugin.

**Comment by tehkillerbee** [comment]
FYI, the tidalapi has been updated with OAuth support in the latest 0.6.8 version. This means it should be possible to add support for High res quality. However, changes are needed in both tidalapi and this plugin to make it possible.

**Comment by bikebandit101** [comment]
Hey @tehkillerbee I saw your post sorry I have gotten back sooner, I moved back home and got new job. Needless to say things have been crazy. I saw all the back forth about the update. Looks promising. Let me know if there is something you need to do for help. Thanks,

**Comment by DerNuntius** [comment]
> I doubt that reaching out to Tidal would give us any more information. But there are a couple of instructions listed here: https://github.com/tidal-engineering/passport-tidal. There is also a discussion here regarding getting API access [MusicPlayerDaemon/MPD#545](https://github.com/MusicPlayerDaemon/MPD/issues/545)
> Quoting jonaski in the above thread: "I don't think Tidal would approve an open source project where the client id can be seen in the source code. And without the client id no-one can use it."
> 
> In any case, the tidalAPI has been reverse engineered by DerNuntius and others (see https://github.com/Fokka-Engineering/TIDAL/wiki for more information). I would probably look at https://github.com/Fokka-Engineering/TIDAL/wiki/auth-token for more information about the auth process and see if a similar approach can be implemented for the python-tidal plugin.

I use mopidy-tidal myself and really like it. I'm currently thinking about implementing the libopenTIDAL C library into a mopidy-tidal fork. A libopenTIDAL python wrapper (for a discord bot) is already in use so it's just a matter of rewriting tidal related calls in mopidy-tidal.

MQA reverse engineering is complex and difficult. Only binary blobs and shared libraries are currently capable of decoding/unfolding MQA flacs. I've looked at a couple of implementations, one in java and the other in C++. There is a TIDAL Connect server binary with all the certificates and MQA decoding but understanding disassembled code of an decoder is not an easy task.

**Comment by tehkillerbee** [comment]
@DerNuntius Your suggestion about implementing a libopenTIDAL wrapper sounds like a very a good idea. This will also make the mopidy-tidal plugin less dependent on the python-tidal project, that is not always updated frequently.

Also, I should clarify my earlier messages, as I have been confusing MQA and HIFI quality naming used by Tidal. While HIFI support has previously been added to a fork of mopidy-tidal as previously mentioned, MQA support has definitely not.  HIFI quality is relatively easy to add support for, as far as I understand, but MQA is definitely not. However, support for HiFi quality should be more realistic to support and would be a good place to start, now that OAuth login is supported.

**Comment by prietus** [comment]
hi, I have MQA master subscription to tidal and I'd be very pleased to test anything you'd need.
