### ISSUE TITLE
mopidy-tidal with proxy can't play songs

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#53]
Hi !
I realized that after updating to new versions 2.7 and tidalapi 0.6.10 by entering the proxy credentials in the /etc/mopidy/mopidy.conf, mopidy-tidal connects regularly **but cannot play audio**.
Without the proxy credentials, everything works fine.
You can check ? many thanks !

**Comment by tehkillerbee** [comment]
@chicco64 You do not need the proxy credentials any longer since tidalapi has been updated. Maybe the client_id/secret you are using is not working any longer? It could also be that you are using wrong stream type for the credentials you are using, i.e. you are trying to stream HIGH using a LOSSLESS client_id/secret combo

**Comment by chicco64** [comment]
I am not referring to the tidalapi credentials, but to the mopidy configuration file, this is the section:

# /etc/mopidy/mopidy.conf

[proxy]
scheme = http
hostname =
port =
username =
password =

Before it worked perfectly; with other services (e.g. Spotify) as well.

**Comment by tehkillerbee** [comment]
Sorry, I misunderstood you then.

Does using a proxy break other services (Spotify etc) as well? In any case, I doubt this is related to the recent tidalapi updates - unless Tidal blocks use of proxy servers.

**Comment by tehkillerbee** [comment]
Closing this issue due to no updates.
